;; (setq auto-install-directory "~/.emacs.d/auto-install/")
;; (add-to-list 'load-path auto-install-directory)
;; (require 'auto-install)
;; (auto-install-update-emacswiki-package-name t)
;; (auto-install-compatibility-setup)
